<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf\FlightSummary;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.FlightSummary.Itinerary</code>
 */
class Itinerary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary.Sector sector = 1;</code>
     */
    protected $sector = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector $sector
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary.Sector sector = 1;</code>
     * @return \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector|null
     */
    public function getSector()
    {
        return $this->sector;
    }

    public function hasSector()
    {
        return isset($this->sector);
    }

    public function clearSector()
    {
        unset($this->sector);
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary.Sector sector = 1;</code>
     * @param \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector $var
     * @return $this
     */
    public function setSector($var)
    {
        GPBUtil::checkMessage($var, \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector::class);
        $this->sector = $var;

        return $this;
    }

}

