#!/usr/bin/env php
<?php
include __DIR__ . '/vendor/autoload.php';
if (!class_exists('Symfony\Component\Console\Application')) {
    echo "Symfony console is not installed. Please install dev dependencies";
}

use Mintopia\Flights\Commands\CompileCommand;
use Mintopia\Flights\Commands\SearchCommand;
use Symfony\Component\Console\Application;

$application = new Application('Flights CLI', '1.0.0');
$application->addCommands([
    new SearchCommand(),
    new CompileCommand(),
]);
$application->run();