<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.Airport</code>
 */
class Airport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sint32 flag = 1;</code>
     */
    protected $flag = 0;
    /**
     * Generated from protobuf field <code>string airport = 2;</code>
     */
    protected $airport = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $flag
     *     @type string $airport
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sint32 flag = 1;</code>
     * @return int
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>sint32 flag = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string airport = 2;</code>
     * @return string
     */
    public function getAirport()
    {
        return $this->airport;
    }

    /**
     * Generated from protobuf field <code>string airport = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAirport($var)
    {
        GPBUtil::checkString($var, True);
        $this->airport = $var;

        return $this;
    }

}

