<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.FlightData</code>
 */
class FlightData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string date = 2;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>repeated .protobuf.ItineraryData itin_data = 4;</code>
     */
    private $itin_data;
    /**
     * Generated from protobuf field <code>optional int32 max_stops = 5;</code>
     */
    protected $max_stops = null;
    /**
     * Generated from protobuf field <code>repeated string airlines = 6;</code>
     */
    private $airlines;
    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport from_flight = 13;</code>
     */
    private $from_flight;
    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport to_flight = 14;</code>
     */
    private $to_flight;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $date
     *     @type \Mintopia\Flights\Protobuf\ItineraryData[] $itin_data
     *     @type int $max_stops
     *     @type string[] $airlines
     *     @type \Mintopia\Flights\Protobuf\Airport[] $from_flight
     *     @type \Mintopia\Flights\Protobuf\Airport[] $to_flight
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.ItineraryData itin_data = 4;</code>
     * @return RepeatedField<\Mintopia\Flights\Protobuf\ItineraryData>
     */
    public function getItinData()
    {
        return $this->itin_data;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.ItineraryData itin_data = 4;</code>
     * @param \Mintopia\Flights\Protobuf\ItineraryData[] $var
     * @return $this
     */
    public function setItinData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mintopia\Flights\Protobuf\ItineraryData::class);
        $this->itin_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 max_stops = 5;</code>
     * @return int
     */
    public function getMaxStops()
    {
        return isset($this->max_stops) ? $this->max_stops : 0;
    }

    public function hasMaxStops()
    {
        return isset($this->max_stops);
    }

    public function clearMaxStops()
    {
        unset($this->max_stops);
    }

    /**
     * Generated from protobuf field <code>optional int32 max_stops = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxStops($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_stops = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string airlines = 6;</code>
     * @return RepeatedField<string>
     */
    public function getAirlines()
    {
        return $this->airlines;
    }

    /**
     * Generated from protobuf field <code>repeated string airlines = 6;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAirlines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->airlines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport from_flight = 13;</code>
     * @return RepeatedField<\Mintopia\Flights\Protobuf\Airport>
     */
    public function getFromFlight()
    {
        return $this->from_flight;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport from_flight = 13;</code>
     * @param \Mintopia\Flights\Protobuf\Airport[] $var
     * @return $this
     */
    public function setFromFlight($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mintopia\Flights\Protobuf\Airport::class);
        $this->from_flight = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport to_flight = 14;</code>
     * @return RepeatedField<\Mintopia\Flights\Protobuf\Airport>
     */
    public function getToFlight()
    {
        return $this->to_flight;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Airport to_flight = 14;</code>
     * @param \Mintopia\Flights\Protobuf\Airport[] $var
     * @return $this
     */
    public function setToFlight($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mintopia\Flights\Protobuf\Airport::class);
        $this->to_flight = $arr;

        return $this;
    }

}

