<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.FlightSummary</code>
 */
class FlightSummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Price price = 3;</code>
     */
    protected $price = null;
    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary itinerary = 4;</code>
     */
    protected $itinerary = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currency
     *     @type \Mintopia\Flights\Protobuf\FlightSummary\Price $price
     *     @type \Mintopia\Flights\Protobuf\FlightSummary\Itinerary $itinerary
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Price price = 3;</code>
     * @return \Mintopia\Flights\Protobuf\FlightSummary\Price|null
     */
    public function getPrice()
    {
        return $this->price;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Price price = 3;</code>
     * @param \Mintopia\Flights\Protobuf\FlightSummary\Price $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Mintopia\Flights\Protobuf\FlightSummary\Price::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary itinerary = 4;</code>
     * @return \Mintopia\Flights\Protobuf\FlightSummary\Itinerary|null
     */
    public function getItinerary()
    {
        return $this->itinerary;
    }

    public function hasItinerary()
    {
        return isset($this->itinerary);
    }

    public function clearItinerary()
    {
        unset($this->itinerary);
    }

    /**
     * Generated from protobuf field <code>.protobuf.FlightSummary.Itinerary itinerary = 4;</code>
     * @param \Mintopia\Flights\Protobuf\FlightSummary\Itinerary $var
     * @return $this
     */
    public function setItinerary($var)
    {
        GPBUtil::checkMessage($var, \Mintopia\Flights\Protobuf\FlightSummary\Itinerary::class);
        $this->itinerary = $var;

        return $this;
    }

}

