<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.Info</code>
 */
class Info extends \Google\Protobuf\Internal\Message
{
    /**
     * zig-zag(14)=28 → varint 0x1c
     *
     * Generated from protobuf field <code>sint32 flag_1 = 1;</code>
     */
    protected $flag_1 = 0;
    /**
     * zig-zag(1)=2  → varint 0x02
     *
     * Generated from protobuf field <code>sint32 flag_2 = 2;</code>
     */
    protected $flag_2 = 0;
    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightData data = 3;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>repeated uint32 passengers = 8;</code>
     */
    private $passengers;
    /**
     * Generated from protobuf field <code>.protobuf.Seat seat = 9;</code>
     */
    protected $seat = 0;
    /**
     * zig-zag(–1)=1 → varint 0x01
     *
     * Generated from protobuf field <code>sint32 flag_3 = 14;</code>
     */
    protected $flag_3 = 0;
    /**
     * Generated from protobuf field <code>.protobuf.Trip trip = 19;</code>
     */
    protected $trip = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $flag_1
     *           zig-zag(14)=28 → varint 0x1c
     *     @type int $flag_2
     *           zig-zag(1)=2  → varint 0x02
     *     @type \Mintopia\Flights\Protobuf\FlightData[] $data
     *     @type int[] $passengers
     *     @type int $seat
     *     @type int $flag_3
     *           zig-zag(–1)=1 → varint 0x01
     *     @type int $trip
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * zig-zag(14)=28 → varint 0x1c
     *
     * Generated from protobuf field <code>sint32 flag_1 = 1;</code>
     * @return int
     */
    public function getFlag1()
    {
        return $this->flag_1;
    }

    /**
     * zig-zag(14)=28 → varint 0x1c
     *
     * Generated from protobuf field <code>sint32 flag_1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag1($var)
    {
        GPBUtil::checkInt32($var);
        $this->flag_1 = $var;

        return $this;
    }

    /**
     * zig-zag(1)=2  → varint 0x02
     *
     * Generated from protobuf field <code>sint32 flag_2 = 2;</code>
     * @return int
     */
    public function getFlag2()
    {
        return $this->flag_2;
    }

    /**
     * zig-zag(1)=2  → varint 0x02
     *
     * Generated from protobuf field <code>sint32 flag_2 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag2($var)
    {
        GPBUtil::checkInt32($var);
        $this->flag_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightData data = 3;</code>
     * @return RepeatedField<\Mintopia\Flights\Protobuf\FlightData>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightData data = 3;</code>
     * @param \Mintopia\Flights\Protobuf\FlightData[] $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mintopia\Flights\Protobuf\FlightData::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 passengers = 8;</code>
     * @return RepeatedField<int>
     */
    public function getPassengers()
    {
        return $this->passengers;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 passengers = 8;</code>
     * @param int[] $var
     * @return $this
     */
    public function setPassengers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->passengers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.Seat seat = 9;</code>
     * @return int
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * Generated from protobuf field <code>.protobuf.Seat seat = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setSeat($var)
    {
        GPBUtil::checkEnum($var, \Mintopia\Flights\Protobuf\Seat::class);
        $this->seat = $var;

        return $this;
    }

    /**
     * zig-zag(–1)=1 → varint 0x01
     *
     * Generated from protobuf field <code>sint32 flag_3 = 14;</code>
     * @return int
     */
    public function getFlag3()
    {
        return $this->flag_3;
    }

    /**
     * zig-zag(–1)=1 → varint 0x01
     *
     * Generated from protobuf field <code>sint32 flag_3 = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag3($var)
    {
        GPBUtil::checkInt32($var);
        $this->flag_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.Trip trip = 19;</code>
     * @return int
     */
    public function getTrip()
    {
        return $this->trip;
    }

    /**
     * Generated from protobuf field <code>.protobuf.Trip trip = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkEnum($var, \Mintopia\Flights\Protobuf\Trip::class);
        $this->trip = $var;

        return $this;
    }

}

