<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.ItineraryData</code>
 */
class ItineraryData extends \Google\Protobuf\Internal\Message
{
    /**
     * KUN
     *
     * Generated from protobuf field <code>string departure_airport = 1;</code>
     */
    protected $departure_airport = '';
    /**
     * 2025-07-20
     *
     * Generated from protobuf field <code>string departure_date = 2;</code>
     */
    protected $departure_date = '';
    /**
     * MAD
     *
     * Generated from protobuf field <code>string arrival_airport = 3;</code>
     */
    protected $arrival_airport = '';
    /**
     * FR
     *
     * Generated from protobuf field <code>string flight_code = 5;</code>
     */
    protected $flight_code = '';
    /**
     * 103
     *
     * Generated from protobuf field <code>string flight_number = 6;</code>
     */
    protected $flight_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $departure_airport
     *           KUN
     *     @type string $departure_date
     *           2025-07-20
     *     @type string $arrival_airport
     *           MAD
     *     @type string $flight_code
     *           FR
     *     @type string $flight_number
     *           103
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * KUN
     *
     * Generated from protobuf field <code>string departure_airport = 1;</code>
     * @return string
     */
    public function getDepartureAirport()
    {
        return $this->departure_airport;
    }

    /**
     * KUN
     *
     * Generated from protobuf field <code>string departure_airport = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartureAirport($var)
    {
        GPBUtil::checkString($var, True);
        $this->departure_airport = $var;

        return $this;
    }

    /**
     * 2025-07-20
     *
     * Generated from protobuf field <code>string departure_date = 2;</code>
     * @return string
     */
    public function getDepartureDate()
    {
        return $this->departure_date;
    }

    /**
     * 2025-07-20
     *
     * Generated from protobuf field <code>string departure_date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartureDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->departure_date = $var;

        return $this;
    }

    /**
     * MAD
     *
     * Generated from protobuf field <code>string arrival_airport = 3;</code>
     * @return string
     */
    public function getArrivalAirport()
    {
        return $this->arrival_airport;
    }

    /**
     * MAD
     *
     * Generated from protobuf field <code>string arrival_airport = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setArrivalAirport($var)
    {
        GPBUtil::checkString($var, True);
        $this->arrival_airport = $var;

        return $this;
    }

    /**
     * FR
     *
     * Generated from protobuf field <code>string flight_code = 5;</code>
     * @return string
     */
    public function getFlightCode()
    {
        return $this->flight_code;
    }

    /**
     * FR
     *
     * Generated from protobuf field <code>string flight_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFlightCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->flight_code = $var;

        return $this;
    }

    /**
     * 103
     *
     * Generated from protobuf field <code>string flight_number = 6;</code>
     * @return string
     */
    public function getFlightNumber()
    {
        return $this->flight_number;
    }

    /**
     * 103
     *
     * Generated from protobuf field <code>string flight_number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFlightNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->flight_number = $var;

        return $this;
    }

}

