<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.ItinerarySummary</code>
 */
class ItinerarySummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string flights = 2;</code>
     */
    protected $flights = '';
    /**
     * Generated from protobuf field <code>.protobuf.Price price = 3;</code>
     */
    protected $price = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $flights
     *     @type \Mintopia\Flights\Protobuf\Price $price
     * }
     */
    public function __construct($data = NULL) {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string flights = 2;</code>
     * @return string
     */
    public function getFlights()
    {
        return $this->flights;
    }

    /**
     * Generated from protobuf field <code>string flights = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFlights($var)
    {
        GPBUtil::checkString($var, True);
        $this->flights = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.Price price = 3;</code>
     * @return \Mintopia\Flights\Protobuf\Price|null
     */
    public function getPrice()
    {
        return $this->price;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Price price = 3;</code>
     * @param \Mintopia\Flights\Protobuf\Price $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Mintopia\Flights\Protobuf\Price::class);
        $this->price = $var;

        return $this;
    }

}

