<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>protobuf.Passenger</code>
 */
class Passenger
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PASSENGER = 0;</code>
     */
    const UNKNOWN_PASSENGER = 0;
    /**
     * Generated from protobuf enum <code>ADULT = 1;</code>
     */
    const ADULT = 1;
    /**
     * Generated from protobuf enum <code>CHILD = 2;</code>
     */
    const CHILD = 2;
    /**
     * Generated from protobuf enum <code>INFANT_IN_SEAT = 3;</code>
     */
    const INFANT_IN_SEAT = 3;
    /**
     * Generated from protobuf enum <code>INFANT_ON_LAP = 4;</code>
     */
    const INFANT_ON_LAP = 4;

    private static $valueToName = [
        self::UNKNOWN_PASSENGER => 'UNKNOWN_PASSENGER',
        self::ADULT => 'ADULT',
        self::CHILD => 'CHILD',
        self::INFANT_IN_SEAT => 'INFANT_IN_SEAT',
        self::INFANT_ON_LAP => 'INFANT_ON_LAP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

