<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>protobuf.Seat</code>
 */
class Seat
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_SEAT = 0;</code>
     */
    const UNKNOWN_SEAT = 0;
    /**
     * Generated from protobuf enum <code>ECONOMY = 1;</code>
     */
    const ECONOMY = 1;
    /**
     * Generated from protobuf enum <code>PREMIUM_ECONOMY = 2;</code>
     */
    const PREMIUM_ECONOMY = 2;
    /**
     * Generated from protobuf enum <code>BUSINESS = 3;</code>
     */
    const BUSINESS = 3;
    /**
     * Generated from protobuf enum <code>FIRST = 4;</code>
     */
    const FIRST = 4;

    private static $valueToName = [
        self::UNKNOWN_SEAT => 'UNKNOWN_SEAT',
        self::ECONOMY => 'ECONOMY',
        self::PREMIUM_ECONOMY => 'PREMIUM_ECONOMY',
        self::BUSINESS => 'BUSINESS',
        self::FIRST => 'FIRST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                __CLASS__,
                $value
            ));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                __CLASS__,
                $name
            ));
        }
        return constant($const);
    }
}
