<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>protobuf.Trip</code>
 */
class Trip
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_TRIP = 0;</code>
     */
    const UNKNOWN_TRIP = 0;
    /**
     * Generated from protobuf enum <code>ROUND_TRIP = 1;</code>
     */
    const ROUND_TRIP = 1;
    /**
     * Generated from protobuf enum <code>ONE_WAY = 2;</code>
     */
    const ONE_WAY = 2;
    /**
     * not implemented
     *
     * Generated from protobuf enum <code>MULTI_CITY = 3;</code>
     */
    const MULTI_CITY = 3;

    private static $valueToName = [
        self::UNKNOWN_TRIP => 'UNKNOWN_TRIP',
        self::ROUND_TRIP => 'ROUND_TRIP',
        self::ONE_WAY => 'ONE_WAY',
        self::MULTI_CITY => 'MULTI_CITY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                __CLASS__,
                $value
            ));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                __CLASS__,
                $name
            ));
        }
        return constant($const);
    }
}
