<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf\FlightSummary\Itinerary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.FlightSummary.Itinerary.Sector</code>
 */
class Sector extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightSummary.Itinerary.Sector.Flight flight = 1;</code>
     */
    private $flight;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector\Flight[] $flight
     * }
     */
    public function __construct($data = null)
    {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightSummary.Itinerary.Sector.Flight flight = 1;</code>
     * @return RepeatedField<\Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector\Flight>
     */
    public function getFlight()
    {
        return $this->flight;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.FlightSummary.Itinerary.Sector.Flight flight = 1;</code>
     * @param \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector\Flight[] $var
     * @return $this
     */
    public function setFlight($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector\Flight::class);
        $this->flight = $arr;

        return $this;
    }
}
