<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto

namespace Mintopia\Flights\Protobuf\FlightSummary\Itinerary\Sector;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protobuf.FlightSummary.Itinerary.Sector.Flight</code>
 */
class Flight extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string from = 1;</code>
     */
    protected $from = '';
    /**
     * Generated from protobuf field <code>string departure = 2;</code>
     */
    protected $departure = '';
    /**
     * Generated from protobuf field <code>string to = 3;</code>
     */
    protected $to = '';
    /**
     * Generated from protobuf field <code>string arrival = 4;</code>
     */
    protected $arrival = '';
    /**
     * Generated from protobuf field <code>string airline = 5;</code>
     */
    protected $airline = '';
    /**
     * Generated from protobuf field <code>string number = 6;</code>
     */
    protected $number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $from
     *     @type string $departure
     *     @type string $to
     *     @type string $arrival
     *     @type string $airline
     *     @type string $number
     * }
     */
    public function __construct($data = null)
    {
        \Mintopia\Flights\Protobuf\Metadata\Flights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, true);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string departure = 2;</code>
     * @return string
     */
    public function getDeparture()
    {
        return $this->departure;
    }

    /**
     * Generated from protobuf field <code>string departure = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeparture($var)
    {
        GPBUtil::checkString($var, true);
        $this->departure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to = 3;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>string to = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, true);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string arrival = 4;</code>
     * @return string
     */
    public function getArrival()
    {
        return $this->arrival;
    }

    /**
     * Generated from protobuf field <code>string arrival = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setArrival($var)
    {
        GPBUtil::checkString($var, true);
        $this->arrival = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string airline = 5;</code>
     * @return string
     */
    public function getAirline()
    {
        return $this->airline;
    }

    /**
     * Generated from protobuf field <code>string airline = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAirline($var)
    {
        GPBUtil::checkString($var, true);
        $this->airline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string number = 6;</code>
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>string number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, true);
        $this->number = $var;

        return $this;
    }
}
